# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1904c2193c75f4b619bf16d764ea5b42406325de261aafffa01e6fd30787bf0d5d39678e0a731e93a014d486069138a64c5b052e8c52e51deba7f7b79680ffc6

test:
  secret_key_base: 626b625bf1c367dd699ed222302f90e1223d6edfc6832ae47f32ebadd7a77ee51d20f215dc533167cbe6b97d410bc593be3a9bbe7bc6f54649d702e69f649b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
